// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/torrent_bridge.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class BetterLibtorrentFlutterBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  BetterLibtorrentFlutterBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  BetterLibtorrentFlutterBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int te_ping() {
    return _te_ping();
  }

  late final _te_pingPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>('te_ping');
  late final _te_ping = _te_pingPtr.asFunction<int Function()>();
}
