name: Build Linux Deps

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-linux-deps:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build OpenSSL
        run: bash build_scripts/build_openssl.sh --target=linux-x86_64 --output=$PWD/out/linux/linux-x86_64
      - name: Build libdatachannel
        run: bash build_scripts/build_libdatachannel.sh --target=linux-x86_64 --output=$PWD/out/linux/linux-x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deps-linux-linux-x86_64
          path: out/linux/linux-x86_64
