name: Build iOS Deps

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_call:

jobs:
  build-ios:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [iossimulator-xcrun-x86_64, iossimulator-xcrun-arm64, ios64-cross-arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build OpenSSL
        run: |
          bash build_scripts/build_openssl.sh --target=${{ matrix.target }} --output=$PWD/out/ios/${{ matrix.target }}
      - name: Build libdatachannel
        run: |
          bash build_scripts/build_libdatachannel.sh --target=${{ matrix.target }} --output=$PWD/out/ios/${{ matrix.target }}
      - name: Build libtorrent and Engine
        run: |
          bash build_scripts/build_libtorrent.sh --target=${{ matrix.target }} --deps=$PWD/out/ios/${{ matrix.target }} --output=$PWD/out/final/ios/${{ matrix.target }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: engine-ios-${{ matrix.target }}
          path: out/final/ios/${{ matrix.target }}

  package-ios:
    needs: build-ios
    runs-on: macos-latest
    steps:
      - name: Download all iOS engine artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: engine-ios-*
          path: out/
      - name: Create XCFramework
        run: |
          lipo -create out/engine-ios-iossimulator-xcrun-arm64/bin/libtorrent_engine.a out/engine-ios-iossimulator-xcrun-x86_64/bin/libtorrent_engine.a -output libtorrent_engine_sim.a
          xcodebuild -create-xcframework \
            -library out/engine-ios-ios64-cross-arm64/bin/libtorrent_engine.a \
            -library libtorrent_engine_sim.a \
            -output TorrentEngine.xcframework
      - name: Upload iOS XCFramework
        uses: actions/upload-artifact@v4
        with:
          name: final-ios
          path: TorrentEngine.xcframework
