name: Build Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deps-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [android-arm64, android-arm, android-x86_64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build OpenSSL
        run: bash build_scripts/build_openssl.sh --target=${{ matrix.target }} --output=$PWD/out/android/${{ matrix.target }}
      - name: Build libdatachannel
        run: bash build_scripts/build_libdatachannel.sh --target=${{ matrix.target }} --output=$PWD/out/android/${{ matrix.target }}
      - name: Upload deps artifact
        uses: actions/upload-artifact@v4
        with:
          name: deps-${{ matrix.target }}
          path: out/android/${{ matrix.target }}

  build-libtorrent-android:
    needs: build-deps-android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: android-arm64
            abi: arm64-v8a
          - target: android-arm
            abi: armeabi-v7a
          - target: android-x86_64
            abi: x86_64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Android NDK
        run: echo "ANDROID_NDK_ROOT=$ANDROID_NDK_HOME" >> $GITHUB_ENV
      - name: Download deps artifact
        uses: actions/download-artifact@v4
        with:
          name: deps-${{ matrix.target }}
          path: third_party/prebuilt/android/${{ matrix.abi }}
      - name: Setup Boost Headers
        run: |
          cd third_party/boost
          ./bootstrap.sh
          ./b2 headers
      - name: Build libtorrent and Engine
        run: bash build_scripts/build_libtorrent.sh --target=${{ matrix.target }} --deps=$PWD/third_party/prebuilt/android/${{ matrix.abi }} --output=$PWD/android/src/main/jniLibs/${{ matrix.abi }}
      - name: Upload final artifact
        uses: actions/upload-artifact@v4
        with:
          name: engine-${{ matrix.target }}
          path: android/src/main/jniLibs/${{ matrix.abi }}
