name: Build Windows Deps

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-windows-deps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.5.1
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: Build OpenSSL
        run: bash build_scripts/build_openssl.sh --target=VC-WIN64A --output=$PWD/out/windows/VC-WIN64A
      - name: Build libdatachannel
        run: bash build_scripts/build_libdatachannel.sh --target=VC-WIN64A --output=$PWD/out/windows/VC-WIN64A
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deps-windows-VC-WIN64A
          path: out/windows/VC-WIN64A
