name: Build Android Deps

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-android-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [android-arm64, android-arm, android-x86_64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27b
      - name: Build OpenSSL
        run: |
          export ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}
          export PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          bash build_scripts/build_openssl.sh --target=${{ matrix.target }} --output=$PWD/out/android/${{ matrix.target }}
      - name: Build libdatachannel
        run: |
          export ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}
          bash build_scripts/build_libdatachannel.sh --target=${{ matrix.target }} --output=$PWD/out/android/${{ matrix.target }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deps-${{ matrix.target }}
          path: out/android/${{ matrix.target }}
